default_platform(:ios)

platform :ios do
  desc "Runs unit tests on iPhone 12 mini"
  lane :iphone12mini_tests do
    run_tests(devices: ["iPhone 12 mini"],
              scheme: "Demo",
	      cloned_source_packages_path: "SourcePackages")
  end
end
